// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Account struct {
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type CreateRoleInput struct {
	DisplayName string              `json:"displayName"`
	Description *string             `json:"description"`
	Permissions []*PermissionsInput `json:"permissions"`
}

type CreateUserInput struct {
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phoneNumber"`
}

type DeleteUserPayload struct {
	Success bool `json:"success"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type PageInfo struct {
	HasNextPage bool `json:"hasNextPage"`
}

type Permission struct {
	Method string `json:"method"`
}

type PermissionsInput struct {
	Method string `json:"method"`
}

type RegisterPayload struct {
	Token string `json:"token"`
}

type Role struct {
	ID          string        `json:"id"`
	DisplayName string        `json:"displayName"`
	Description *string       `json:"description"`
	Permissions []*Permission `json:"permissions"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type RoleEdge struct {
	Node   *Role  `json:"node"`
	Cursor string `json:"cursor"`
}

type RolesConnection struct {
	TotalCount int         `json:"totalCount"`
	Edges      []*RoleEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
}

type UpdateAccountInput struct {
	DisplayName *string `json:"displayName"`
}

type UpdateRoleInput struct {
	DisplayName *string             `json:"displayName"`
	Description *string             `json:"description"`
	Permissions []*PermissionsInput `json:"permissions"`
}

type UpdateUserInput struct {
	FirstName   *string `json:"firstName"`
	LastName    *string `json:"lastName"`
	Email       *string `json:"email"`
	PhoneNumber *string `json:"phoneNumber"`
}

type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}

type UsersConnection struct {
	TotalCount int         `json:"totalCount"`
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
}
